# Generated by Django 3.0.3 on 2020-02-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='sex',
        ),
    ]
