# Generated by Django 3.0.3 on 2020-02-12 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologist', '0005_auto_20200212_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default='somestring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='somestring', max_length=50),
            preserve_default=False,
        ),
    ]
