# Generated by Django 3.0.3 on 2020-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologist', '0007_auto_20200212_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
