# Generated by Django 3.0.3 on 2020-02-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologist', '0011_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
