# Generated by Django 3.0.3 on 2020-02-12 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutriologist', '0012_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nutriologist',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutriologist.Patients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
