# Generated by Django 3.0.3 on 2020-02-13 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologist', '0015_auto_20200212_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsplan',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 13)),
        ),
        migrations.AlterField(
            model_name='patientstats',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 13)),
        ),
    ]
